//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RisaAtelier.MultipurposeLib.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RisaAtelier.MultipurposeLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Create New DataTable From Array of DataRow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityDesc_Convert_DataTable_FromDataRowArray {
            get {
                return ResourceManager.GetString("ActivityDesc_Convert_DataTable_FromDataRowArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert From String To SecureString に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityDesc_Convert_SecureString_FromString {
            get {
                return ResourceManager.GetString("ActivityDesc_Convert_SecureString_FromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert From SecureString To String に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityDesc_Convert_SecureString_ToString {
            get {
                return ResourceManager.GetString("ActivityDesc_Convert_SecureString_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copies DataTable contents to Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityDesc_DataTable_CopyToClipboard {
            get {
                return ResourceManager.GetString("ActivityDesc_DataTable_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Joint DataTable Laterally に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityDesc_DataTable_JointTable {
            get {
                return ResourceManager.GetString("ActivityDesc_DataTable_JointTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rebuild DataTable with swapping Rows And Columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityDesc_DataTable_SwapRowsAndColumns {
            get {
                return ResourceManager.GetString("ActivityDesc_DataTable_SwapRowsAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets Excel Active Worksheet&apos;s Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityDesc_Excel_GetActiveSheetName {
            get {
                return ResourceManager.GetString("ActivityDesc_Excel_GetActiveSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set / Disable &quot;Recommend Read Only&quot; Status to Excel file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityDesc_Excel_ReadReccomendSetting {
            get {
                return ResourceManager.GetString("ActivityDesc_Excel_ReadReccomendSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting file writing complete, like downloading file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityDesc_File_WaitForFileGrowthCompleted {
            get {
                return ResourceManager.GetString("ActivityDesc_File_WaitForFileGrowthCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From Array of DataRow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityName_Convert_DataTable_FromDataRowArray {
            get {
                return ResourceManager.GetString("ActivityName_Convert_DataTable_FromDataRowArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From String To SecureString に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityName_Convert_SecureString_FromString {
            get {
                return ResourceManager.GetString("ActivityName_Convert_SecureString_FromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From SecureString To String に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityName_Convert_SecureString_ToString {
            get {
                return ResourceManager.GetString("ActivityName_Convert_SecureString_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy To Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityName_DataTable_CopyToClipboard {
            get {
                return ResourceManager.GetString("ActivityName_DataTable_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Joint DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityName_DataTable_JointTable {
            get {
                return ResourceManager.GetString("ActivityName_DataTable_JointTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swap Rows And Columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityName_DataTable_SwapRowsAndColumns {
            get {
                return ResourceManager.GetString("ActivityName_DataTable_SwapRowsAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Active Sheet Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityName_Excel_GetActiveSheetName {
            get {
                return ResourceManager.GetString("ActivityName_Excel_GetActiveSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read Recommend Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityName_Excel_ReadReccomendSetting {
            get {
                return ResourceManager.GetString("ActivityName_Excel_ReadReccomendSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wait For Writing File Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityName_File_WaitForFileGrowthCompleted {
            get {
                return ResourceManager.GetString("ActivityName_File_WaitForFileGrowthCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Risa Atelier.Convert.DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityTree_Convert_DataTable_FromDataRowArray {
            get {
                return ResourceManager.GetString("ActivityTree_Convert_DataTable_FromDataRowArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Risa Atelier.Convert.SecureString に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityTree_Convert_SecureString_FromString {
            get {
                return ResourceManager.GetString("ActivityTree_Convert_SecureString_FromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Risa Atelier.Convert.SecureString に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityTree_Convert_SecureString_ToString {
            get {
                return ResourceManager.GetString("ActivityTree_Convert_SecureString_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Risa Atelier.DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityTree_DataTable_CopyToClipboard {
            get {
                return ResourceManager.GetString("ActivityTree_DataTable_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Risa Atelier.DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityTree_DataTable_JointTable {
            get {
                return ResourceManager.GetString("ActivityTree_DataTable_JointTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Risa Atelier.DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityTree_DataTable_SwapRowsAndColumns {
            get {
                return ResourceManager.GetString("ActivityTree_DataTable_SwapRowsAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Risa Atelier.Excel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityTree_Excel_GetActiveSheetName {
            get {
                return ResourceManager.GetString("ActivityTree_Excel_GetActiveSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Risa Atelier.Excel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityTree_Excel_ReadRecommendSetting {
            get {
                return ResourceManager.GetString("ActivityTree_Excel_ReadRecommendSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Risa Atelier.File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivityTree_File_WaitForFileGrowthCompleted {
            get {
                return ResourceManager.GetString("ActivityTree_File_WaitForFileGrowthCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_DataTable_FDArr_InArgCategory1 {
            get {
                return ResourceManager.GetString("Convert_DataTable_FDArr_InArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Array of DataRow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_DataTable_FDArr_InArgDesc1 {
            get {
                return ResourceManager.GetString("Convert_DataTable_FDArr_InArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Array of DataRow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_DataTable_FDArr_InArgName1 {
            get {
                return ResourceManager.GetString("Convert_DataTable_FDArr_InArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_DataTable_FDArr_OutArgCategory1 {
            get {
                return ResourceManager.GetString("Convert_DataTable_FDArr_OutArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable from Array of DataRow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_DataTable_FDArr_OutArgDesc1 {
            get {
                return ResourceManager.GetString("Convert_DataTable_FDArr_OutArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Built DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_DataTable_FDArr_OutArgName1 {
            get {
                return ResourceManager.GetString("Convert_DataTable_FDArr_OutArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_FS_InArgCategory1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_FS_InArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_FS_InArgDesc1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_FS_InArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input (String) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_FS_InArgName1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_FS_InArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_FS_OutArgCategory1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_FS_OutArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_FS_OutArgDesc1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_FS_OutArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output (SecureString) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_FS_OutArgName1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_FS_OutArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_TS_InArgCategory1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_TS_InArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SecureString Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_TS_InArgDesc1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_TS_InArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input (SecureString) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_TS_InArgName1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_TS_InArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_TS_OutArgCategory1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_TS_OutArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_TS_OutArgDesc1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_TS_OutArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output (String) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert_SecureString_TS_OutArgName1 {
            get {
                return ResourceManager.GetString("Convert_SecureString_TS_OutArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgCategory1 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgCategory2 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgCategory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgCategory3 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgCategory3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgCategory4 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgCategory4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgDesc1 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format of DateTime type field に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgDesc2 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Escape Special chars (NewLine, Double Quotation, etc) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgDesc3 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sepalater に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgDesc4 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgName1 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DateTime Type Comvert Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgName2 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Escape Special chars に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgName3 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_CTC_InArgName4 {
            get {
                return ResourceManager.GetString("DataTable_CTC_InArgName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input (Left) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgCategory1 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input (Right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgCategory2 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgCategory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input (Left) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgCategory3 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgCategory3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input (Right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgCategory4 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgCategory4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgCategory5 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgCategory5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source DataTable (Left Side) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgDesc1 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source DataTable (Right Side) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgDesc2 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort Condition of DataTable (Left Side) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgDesc3 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort Condition of DataTable (Right Side) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgDesc4 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Records Counts are Same. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgDesc5 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgDesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable (Left) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgName1 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable (Right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgName2 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort Condition (Left) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgName3 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort Condition (Right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgName4 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Records Counts are Same. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_InArgName5 {
            get {
                return ResourceManager.GetString("DataTable_JT_InArgName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_OutArgCategory1 {
            get {
                return ResourceManager.GetString("DataTable_JT_OutArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merged DataTable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_OutArgDesc1 {
            get {
                return ResourceManager.GetString("DataTable_JT_OutArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_JT_OutArgName1 {
            get {
                return ResourceManager.GetString("DataTable_JT_OutArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_SRAC_InArgCategory1 {
            get {
                return ResourceManager.GetString("DataTable_SRAC_InArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_SRAC_InArgDesc1 {
            get {
                return ResourceManager.GetString("DataTable_SRAC_InArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_SRAC_InArgName1 {
            get {
                return ResourceManager.GetString("DataTable_SRAC_InArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_SRAC_OutArgCategory1 {
            get {
                return ResourceManager.GetString("DataTable_SRAC_OutArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_SRAC_OutArgDesc1 {
            get {
                return ResourceManager.GetString("DataTable_SRAC_OutArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTable_SRAC_OutArgName1 {
            get {
                return ResourceManager.GetString("DataTable_SRAC_OutArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_GASN_OutArgCategory1 {
            get {
                return ResourceManager.GetString("Excel_GASN_OutArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active Worksheet Name of Excel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_GASN_OutArgDesc1 {
            get {
                return ResourceManager.GetString("Excel_GASN_OutArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active Sheet Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_GASN_OutArgName1 {
            get {
                return ResourceManager.GetString("Excel_GASN_OutArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_RRS_InArgCategory1 {
            get {
                return ResourceManager.GetString("Excel_RRS_InArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_RRS_InArgCategory2 {
            get {
                return ResourceManager.GetString("Excel_RRS_InArgCategory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_RRS_InArgCategory3 {
            get {
                return ResourceManager.GetString("Excel_RRS_InArgCategory3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If this value set True, Excel application may show &quot;Read Only&quot; recommendation dialog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_RRS_InArgDesc1 {
            get {
                return ResourceManager.GetString("Excel_RRS_InArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Excel Filename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_RRS_InArgDesc2 {
            get {
                return ResourceManager.GetString("Excel_RRS_InArgDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Optional) Set Excel Reading Password \n [CAUTION] Workbook with Read Only Password is not available yet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_RRS_InArgDesc3 {
            get {
                return ResourceManager.GetString("Excel_RRS_InArgDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recommend Read Only Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_RRS_InArgName1 {
            get {
                return ResourceManager.GetString("Excel_RRS_InArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel Filename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_RRS_InArgName2 {
            get {
                return ResourceManager.GetString("Excel_RRS_InArgName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel File Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Excel_RRS_InArgName3 {
            get {
                return ResourceManager.GetString("Excel_RRS_InArgName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel is not running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exception_Excel_Not_Started {
            get {
                return ResourceManager.GetString("Exception_Excel_Not_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of records are not same. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exception_Records_Count_Invalid {
            get {
                return ResourceManager.GetString("Exception_Records_Count_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_InArgCategory1 {
            get {
                return ResourceManager.GetString("File_WFFGC_InArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_InArgCategory2 {
            get {
                return ResourceManager.GetString("File_WFFGC_InArgCategory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_InArgCategory3 {
            get {
                return ResourceManager.GetString("File_WFFGC_InArgCategory3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_InArgDesc1 {
            get {
                return ResourceManager.GetString("File_WFFGC_InArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval of checking file size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_InArgDesc2 {
            get {
                return ResourceManager.GetString("File_WFFGC_InArgDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum time to wait (0 or less : unlimited) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_InArgDesc3 {
            get {
                return ResourceManager.GetString("File_WFFGC_InArgDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Filename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_InArgName1 {
            get {
                return ResourceManager.GetString("File_WFFGC_InArgName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_InArgName2 {
            get {
                return ResourceManager.GetString("File_WFFGC_InArgName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout (Seconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_InArgName3 {
            get {
                return ResourceManager.GetString("File_WFFGC_InArgName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_OutArgCategory1 {
            get {
                return ResourceManager.GetString("File_WFFGC_OutArgCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Size at end. (Bytes) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_OutArgDesc1 {
            get {
                return ResourceManager.GetString("File_WFFGC_OutArgDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed File Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_WFFGC_OutArgName1 {
            get {
                return ResourceManager.GetString("File_WFFGC_OutArgName1", resourceCulture);
            }
        }
    }
}
